### ISSUE TITLE
Beacon age threshold mismatch

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#257]
There is a difference in how the wallet determines that a beacon is out of age when it loads them from disk and when they are fetched through `GetBeaconPublicKey()`. The threshold from disk uses heights with a block generation approximation of 1000 blocks/day while `GetBeaconPublicKey()` uses calendar age. While I think we generate fewer than 1000 blocks/day so the disk loader is more forgiving (loading more beacons than `GetBeaconPublicKey()` allows), we should still make sure they match up. If, for some reason, the situation is switched running nodes will know about more keys than loading nodes so loading nodes could end up with unreachable beacons.

**Comment by startailcoon** [comment]
What I wondered on is what happens if someone compiles a client on their own, commenting out the cache age and runs the client on the network. This was one of the possible solutions for the issue when it started and some people did this change to the code itself. 

If someone does this now they can put beacons in the chain that others can not reach. How can the network prevent this on a global scale rather than relying on a single client to behaving correctly?

If someone creates a block like this I assume they fork and aren't accepted by the network?

**Comment by denravonska** [comment]
@startailcoon Other nodes should reject the blocks, right? I was worried we broke the chain when we had a lot of people doing this during the first sync blackout.

**Comment by gridcoin** [comment]
I think loading the beacons from disk by block age is OK as long as we load more than enough in during boot (especially since the time stamp of the block is the same as the application cache timestamp).

The main concern I see is that the actual block check mechanism only should regard a beacon as valid if its between 0-6 months old, with consistency (even if too many exist in memory).  (Our last mandatory did that). 

But regarding compiling a homebrew client, we rely on 51% to be running the official version and that would mean the supermajority make the right call on approving or denying a block.

All of the homebrew tweaks to force the chain to load are related to allowing the client to load blocks PAST the last "BAD CPID" block where the mandatory version stops with an error.  This is equivalent to us putting a rule in to disregard CPID checks on blocks older than say, 6 hours (similar to the BlockNeedsChecked function).

**Comment by denravonska** [comment]
@gridcoin We will be fine as long as the situation isn't reversed. That is, as long as the runtime check is more strict than the load check.

With the fix I proposed in #256 we get a moving window of 6 months back, starting from the time of the currently known best block. This is how the loader works and I think it's a good solution. We cannot use the system clock since we would either have to load all beacons on startup or implement a more intricate beacon finder.

**Comment by philipswift** [comment]
@gridcoin  What is it 51% of exactly?

All known nodes in history?
All known nodes in last 3 years?
All known nodes that have banscore=0?
All known nodes that have been active in history for 70% of the time?
All known nodes that have only the latest mandatory version?
All known nodes that have the latest version?
All known nodes that are staking?

I think we need exclusions and a minimum quota of work proven within a timeframe otherwise old or out of date nodes will cause problems. Not everyone pro actively searches for information and updates. They would not know to manually update. So maybe as soon as a node/beacon comes online and handshakes, we do tough love and hard code a version check, then update, then restarter.exe download blocks from n, where n is a variable known good state repository, before the wallet GUI appears.

**Comment by gridcoin** [comment]
51% in cryptocurrency is the supermajority of Nodes online at any given time available for block checking.

There are over 250 business logic rules that could be tweaked in the client.  All are equally dangerous when we have rogue hackers tweaking the code.  Lets not look at this from a weak BL standpoint- or philosophically try to imagine things that are wrong with that rule.

The main thing to understand here is that more than 51% need to run the official version, and each business logic rule results in a strong consensus.  This particular rule is deterministic and comes to a strong consensus.

**Comment by philipswift** [comment]
Rogue hackers? :O I'm not trying to work towards imagining anything is wrong with that rule, just how it fits in and if its causing issues by how it is referenced. Is not this an art, not a science?

**Comment by tomasbrod** [comment]
Yes. I remember that this issue was fixed. Please close.

**Comment by pwnorbitals** [comment]
+1 to close

**Comment by RoboticMind** [comment]
Can this be closed?

**Comment by denravonska** [comment]
The bug is still there (age vs height) but we happen to not be affected by it due to the `LoadAdminMessages` range increase in 890de63e8fd325fd84152932bb0f6c1fc36b5e27.
