### ISSUE TITLE
Qt client window can not be resized, content cut off

### ISSUE THREAD

**Issue by eMPee584** [gridcoin-community/Gridcoin-Research#50]
![image](https://cloud.githubusercontent.com/assets/1227833/11316910/160ae388-901a-11e5-9ec6-220a3f7531f2.png)
This is on debian linux with QT 4.8.7+dfsg-4

**Comment by clonedagain** [comment]
It's particularly noticeable in hi-DPI. Lowering the size of screen elements in Ubuntu's Unity (probably in Gnome too) make the elements readable (though very small).

**Comment by eMPee584** [comment]
Oh yeah I always forget about - I also have high-DPI font setting enabled..

**Comment by caraka** [comment]
Howdy eMPee584
I cannot help but notice that the Advanced menu is missing, and wonder if you have used the Ubuntu PPA to install on Debian. If so, I'd love it if you could step through it with me so I (or you) can add it to the Linux pre-compiled page on the wiki at http://wiki.gridcoin.us/Linux_Downloads_%28pre-compiled%29
At some point I'll get around to building a repo for the full debian suite, but until then, helping debian users to get the most out of the PPA is a great step.
You'll notice with the latest build that the Rebuild Block Chain menu is now gone too. There was little in there worth keeping.

**Comment by chri2** [comment]
Hey Richard,

did you see this: http://wiki.gridcoin.us/User:ChriChri#setting_up_on_Debian_Jessie

Could be copied to a new page (and improved) if there is need.

Cheers, Chris

**Comment by ghost** [comment]
I'm seeing the same issue (slightly cut-off text) on Ubuntu 14.04. This wouldn't be a big issue if we could at least resize the window.

v3.5.5.7-g-research

Unlike the original poster, I don't use high-DPI settings in the OS.

**Comment by rtennill** [comment]
i am experiencing this on Windows 7. One screen is 1680x 1050, the other is 2560 x 1440 and I can't read anything below the line containing 'probing coin age' for osme reason. 

It would be nice to have the option to resize and then lock the window size.

**Comment by eMPee584** [comment]
it's just a matter of setting the window and layout properties to resizable.. fairly simple.

**Comment by gridcoin** [comment]
It looks to me like the High DPI settings on new monitors cause either OS (Windows 10 or certain linux flavors: Debian?) to render the HTML default font size larger.

Bitcoin has a similar problem here, and they are waiting for QT beta 5.6 to include certain hints:
https://github.com/bitcoin/bitcoin/issues/7341

I'll see if we can include any font size directive to potentially fix it, or if we will need to compile against 5.6 next.

I am not sure yet if resizing the window will fix the problem - it may change the aspect ratio; but it is worth trying - let me test that.

Rob

**Comment by gridcoin** [comment]
From what I can tell, if we expose the fontsize argument and let the user set fontsize=5 in the gridcoin.conf file, this should fix the problem.  If it does, we can attempt to detect the DPI later, but I need to confirm this first.  It will be in the next release (should be tonight).  If you do not set fontsize we use the default (10).

Rob

**Comment by caraka** [comment]
I experience this across a couple of debian based distros, and I do not use high DPI settings either. Looking forward to testing the fontsize setting in the near future!

If we are going to compile against 5.6 in future, we'll need to address that low priority qt5 compile error I PM'd you about a week or so ago.

**Comment by gridcoin** [comment]
Sounds good - I removed the Gridcoin Browser, so we should now be back where we were before it.  It's close to being ready to check in.

**Comment by rtennill** [comment]
I've updated/restarted my wallet several times and am still having this problem. I have tried fontsize=5 and fontsize=3 but text still gets cut off. I'll grab a screenshot any attach along with any other useful data. 

Also, text overlaps the logo as shown in the screenshot above which is bad. Maybe swap ordering of the text and the logo?

**Comment by ghost** [comment]
Still having cut-off text with 3.5.5.9 on Linux. I added fontsize=3 to gridcoinresearch.conf and restarted the client, that didn't change anything.

![gridcoin](https://cloud.githubusercontent.com/assets/720642/14033355/f7ae29b0-f219-11e5-81d5-6ea81bdd3006.png)

**Comment by caraka** [comment]
I can confirm that the exposure of fontsize= had no effect on my ubuntu builds, with text still not re-formatting to fit the allocated space.

On that note, Rob has indicated that there is an upstream fix, currently in QT5.6 beta, that might address this issue. This issue being the fontsize issue. The window resize isn't really an issue because the window wasn't designed for resizing originally - that will need some more work.

**Comment by gridcoin** [comment]
10-4 on this not working on linux.  It did have an effect on my win7 box, but Im not sure if anyone tested this on win10 yet.
Anyway, I see a blog that suggests that we use font-size in CSS with "points" instead of "pixels" since points are computed internally based on dpi.

Ill test this on windows and then you can test again on linux and see...

**Comment by gridcoin** [comment]
LOL, I think we finally have a solution.  The points and percent did not work, but it does appear that allowing the user to change the max window size (most likely) fixed the issue.

The next release has two new keys:
windowwidth=1200
windowheight=700

Set these higher on high DPI monitors and it appears the text is not cut off.

Rob

**Comment by gridcoin** [comment]
Will someone please test the new feature and let us know if we can close this out?

Thanks!

**Comment by ghost** [comment]
windowheight=600 works for me. Ideally the user wouldn't need to do this manually though, so I'm not sure if it's appropriate to close the issue.

**Comment by sidhujag** [comment]
How is the dev working on this? I see no commits against the issue, you do know how to link issues with commit comments don't you?

**Comment by gridcoin** [comment]
We will revisit again when we move to QT5.

**Comment by RebelSyntax** [comment]
thanks for letting me set this in the conf.  It was driving me nuts!  I finally got everything else working, tweaked my boinc client and projects etc etc... this was the last "major" thing I wanted to get done before I could walk away from it lol, been 2 days!  Thanks again for sharing the info!
