### ISSUE TITLE
Gridcoin Network Traffic bug

### ISSUE THREAD

**Issue by Sekaiji** [gridcoin-community/Gridcoin-Research#718]
Hi,

My gridcoin seems to stop working properly after 5-7 hours of staking.

The debug.log contains this when it's bugging :

10/27/17 04:32:12 UPnP Port Mapping successful.
10/27/17 04:52:14 UPnP Port Mapping successful.
10/27/17 05:12:16 UPnP Port Mapping successful.
10/27/17 05:32:18 UPnP Port Mapping successful.
10/27/17 05:52:20 UPnP Port Mapping successful.

If i have the gridcoin window on top I cannot tell it doesn't work but I won't have anymore reward and if i go in the network traffic i see this :

![2017-10-27_07h56_28](https://user-images.githubusercontent.com/33425299/32448174-79145dc8-c30e-11e7-8c5b-8b4a28b5f0de.png)

If I minimize gridcoin in systray after 5-7 hours I cannot right or left clic on the icon and I have to force close the software.

In both case the process seems working and takes around 2.5% of CPU.

![2017-10-27_07h58_15](https://user-images.githubusercontent.com/33425299/32448185-81c3454c-c30e-11e7-9c25-90df8baca7b9.png)

I have the same behaviour on 3 different hardware configuration since July. So I have this bug before we were in V8.

Now I have this configuration : Win 10 x64 falls creator, last version of boinc.

[debug.log](https://github.com/gridcoin/Gridcoin-Research/files/1446694/debug.log)

**Comment by iFoggz** [comment]
sounds like the current issues we been working toward fixing. whats your debug2.log say/?

also as for networking part it appears that thread could be deadlocked for receiving and sending messages. perhaps this is @denravonska  find and fix to be release in next release?

**Comment by Sekaiji** [comment]
Here's 2 new log files : 

I put a new debug.log file and debug2.log

[debug2.log](https://github.com/gridcoin/Gridcoin-Research/files/1461600/debug2.log)

[debug.zip](https://github.com/gridcoin/Gridcoin-Research/files/1461602/debug.zip)

**Comment by iFoggz** [comment]
from your debug.log file i can see UPnP calls but i see no other network related activity which makes me come to the conclusion that the network thread deadlocked the UPnP calls could be people trying to connect to you,etc. @denravonska maybe that Potential deadlock fix for network thread is solved by this??

**Comment by Sekaiji** [comment]
Hi,
Does it mean it's an known issue and you are working on it ?
I still have the issue.
Thanks

**Comment by tomasbrod** [comment]
@Foggyx420 , the conclusion about network thread being dead-locked is probably right. But UPnP calls do not mean that people are truing to connect to you. UPnP thread (name?) is periodically renewing those UPnP mappings. It is not doing much else, so the network lock-up does not affect it.

**Comment by Sekaiji** [comment]
So... what does it mean ? Is it a bug ? How can i give more information or what can i test to fix this issue ?

**Comment by Sekaiji** [comment]
Everything is working fine since i installed 3.7.0.0
