### ISSUE TITLE
Cannot Advertise Beacon

### ISSUE THREAD

**Issue by moisespr123** [gridcoin-community/Gridcoin-Research#874]
Hi.

For the past few days I've been having this weird issue where the wallet is trying to advertise the beacon but it is unsuccessful.

```

06:08:59
￼
execute advertisebeacon


06:09:00
￼
[
{
"Command" : "advertisebeacon"
},
{
"Result" : "FAIL",
"CPID" : "45272229fb8fca150b3af5136f4799dd",
"Message" : "",
"Errors" : "Error: Unable to send beacon::{\n \"code\" : -4,\n \"message\" : \"Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.\"\n}",
"FAILURE" : "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}
]
```

execute beaconstatus also is saying that my keys are incorrect even if I restored them from previous backups in the backup folder.

What could be wrong here?

If I need to request a beacon delete so that I can exeucte advertisebeacon again, can some of the people in charge of doing so please try deleting my beaconstatus?

Also, I tried checkwallet and repairwallet. Every time I do advertisebeacon it is rejected, then I need to do a repairwallet and I try again but it just doesn't work.

```

06:11:49
￼
repairwallet


06:11:50
￼
{
"mismatched spent coins" : 6,
"amount affected by repair" : 0.03305696
}
```

Then

```

06:12:04
￼
checkwallet


06:12:04
￼
{
"wallet check passed" : true
}
```

I wonder if all of this has to do in that for the past few months I wasn't able to state a block...

**Comment by tomasbrod** [comment]
Please check your logs for errors.
Transactions may be rejected this way when attempting to run development build on production network. What is your version? Dev builds have 4 numbers, release only 3 (the 4th is zero).

**Comment by moisespr123** [comment]
3.7.5.0

I've always ran release versions

**Comment by iFoggz** [comment]
u on a fork or tried restarting wallet?

**Comment by moisespr123** [comment]
* Did upgrade to 3.7.50
* Did restored the chain from a backup I had before
* I doubt I'm in a fork. Difficult was I believe at 3 o 4 at the morning.
Will check in the afternoon.
* Restored previous configuration files as well.

I'll also check the logs in the afternoon.

**Comment by tomasbrod** [comment]
Try to send all your money to yourself.
Try repairwallet.

**Comment by moisespr123** [comment]
This is what the log says:
```
01/26/18 21:18:15 ERROR: AcceptToMemoryPool : bad beacon contract in tx 84ecc13802119f152f4b899199278c674662608db2f824af0f0adf313b2ba809; rejected
01/26/18 21:18:15 CommitTransaction() : Error: Transaction not valid
01/26/18 21:18:15 BEACON ERROR!  Unable to send beacon Error: Unable to send beacon::{
    "code" : -4,
    "message" : "Error: The transaction was rejected.  This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here."
}, 
```

Running the checkwallet, repairwallet, advertisebeacon:
```

17:27:24
￼
checkwallet


17:27:24
￼
{
"mismatched spent coins" : 4,
"amount in question" : 0.02203755
}


17:27:28
￼
repairwallet


17:27:28
￼
{
"mismatched spent coins" : 4,
"amount affected by repair" : 0.02203755
}


17:27:32
￼
checkwallet


17:27:32
￼
{
"wallet check passed" : true
}


17:27:42
￼
execute advertisebeacon


17:27:42
￼
[
{
"Command" : "advertisebeacon"
},
{
"Result" : "FAIL",
"CPID" : "45272229fb8fca150b3af5136f4799dd",
"Message" : "",
"Errors" : "Error: Unable to send beacon::{\n \"code\" : -4,\n \"message\" : \"Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.\"\n}",
"FAILURE" : "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}
]
```

**Comment by moisespr123** [comment]
Interestingly when I use execute beaconstatus it says the timestamp is from 08-25-2017, but on Gridcoinstats, it says it was advertised 3 days ago, possibly in the fork and something seems to be messed up as the client also is trying to advertise the beacon automatically sometimes.

**Comment by iFoggz** [comment]
yes there an issue with cache we going to be addressing. make sure ur on the main chain. and try a restart and if u r on main chain it should reload the cache and correct the beacon contract issue. what happened was the bacon was advertised but the cache shows it less then 5 months. so it rejects it as u already have a new one in cache that is younger then 5 months old. a restart shoudl fix this and rest assured a fix for the beacon contract issue with be addressed with the reorg bug

**Comment by moisespr123** [comment]
I am in the correct chain (Diff above > 4 right now), but the restart doesn't fix the issue

```
09:11:26 |   | execute beaconstatus

{
"Command" : "beaconstatus"
},
{
"CPID" : "45272229fb8fca150b3af5136f4799dd",
"Beacon Exists" : "Yes",
"Beacon Timestamp" : "08-25-2017 23:43:00",
"Public Key" : (removed),
"Private Key" : (removed),
"Local Configuration Public Key" : (removed),
"Magnitude (As of last superblock)" : 75.00000000,
"Block Signing Test Results" : false,
"Errors" : "Local configuration public key does not match beacon public key. This can happen if you copied the wrong public key into your configuration file. Please request that your beacon is deleted, or look into walletbackups for the correct keypair. Failed to sign POR block. This can happen if your keypair is invalid. Check walletbackups for the correct keypair, or request that your beacon is deleted. ",
"Help" : "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon.",
"Configuration Status" : "FAIL"
}
]
```

Thing is, everytime an advertisebeacon is sent from the wallet, the keys in the config file changes, so I assume that's why I see the different keypair error there.

The wallet sent some transactions overnight but they were all rejected. If I keep running the wallet, it will still continue to send the beacon automatically.

I would then need to run repairwallet due to coin mismatch.

I appreciate if this could have a high priority on the issues to be fixed, as I haven't been able to stake a block ever since the end of September or so, which I believed was due to the V8 blocks but I assume there is actually other thing wrong here as even when the V8 kicked off, I was staking maybe 2 to 4 blocks daily.

**Comment by tomasbrod** [comment]
Please turn on debug10 (execute debug10 true) and try again. Post the log.
Also public keys are not secret (they are public). There may be a chance that your beacon is still good, try to search the keys in backups "Public Key" : (removed).

**Comment by iFoggz** [comment]
this has to be related to the cache and beacon contracts.

**Comment by moisespr123** [comment]
```
01/28/18 00:35:39 shortcpid 45272229fb8fca150b3af5136f4799dd, cpid1 45272229fb8fca150b3af5136f4799dd, usercpid 45272229fb8fca150b3af5136f4799dd 

01/28/18 00:35:39 

 Creating beacon for cpid 45272229fb8fca150b3af5136f4799dd, 45272229fb8fca150b3af5136f4799dd406838396b6a68c89798349e986a3f3d3e663a94c2989e679a9c423669993a3c6e706a7466746e64627365706f6241686e626a6d2f64706e;5974e95e9649828c4ec473f6a0e38a28171c82ca488ae74c762031ba44ed8e51;S3U7bnWK6VrL6tMcymL4Jj4pLNNbo6QTYo;040a932d0e227bdf1e0eef6229887bd9088b2b663da8e012946ad543d25e01a6425b892034b3f1e650d404caa56b2483f60cf6da30888b1de998c43d89dc0fa524BackupConfigFile: Copied gridcoinresearch.conf to C:\Users\cardo\AppData\Roaming\GridcoinResearch\walletbackups\gridcoinresearch.conf-2018-01-27T19-39-45
01/28/18 00:35:39 BackupConfigFile: Copied gridcoinresearch.conf to C:\Users\cardo\AppData\Roaming\GridcoinResearch\walletbackups\gridcoinresearch.conf-2018-01-27T19-39-45-beacon
01/28/18 00:35:39 connected 158.69.48.143:32749
01/28/18 00:35:39 send version message: version 180323, blocks=1148323, us=0.0.0.0:0, them=158.69.48.143:32749, peer=158.69.48.143:32749
01/28/18 00:35:39 (842 bytes)
01/28/18 00:35:39 keypool added key 171, size=101
01/28/18 00:35:39 socket closed
01/28/18 00:35:39 disconnecting node 158.69.48.143:32749
01/28/18 00:35:39 VBCTX : Beacon tx publickey != publickey in chain. 040a932d0e227bdf1e0eef6229887bd9088b2b663da8e012946ad543d25e01a6425b892034b3f1e650d404caa56b2483f60cf6da30888b1de998c43d89dc0fa524 != 04028bedc484e9bee432a58bfa236bead98b6e199c5ef55092514af1d185f7a97bed365adf60e6e32f456cd23e0657ab6fb81e641cdc840e2a00526dd016edf6d2
01/28/18 00:35:39 ERROR: AcceptToMemoryPool : bad beacon contract in tx bf01b95d3a74a9e2af4e5eb7110304cd4ad0bcc971a955c516372985480537e2; rejected
01/28/18 00:35:39 CommitTransaction() : Error: Transaction not valid
```

**Comment by tomasbrod** [comment]
You have to delete your old beacon first.

**Comment by moisespr123** [comment]
Perfect! That did fixed the issue!  Thanks! This issue can now be closed as execute beaconstatus reports SUCCESSFUL now.

Thanks all for the help!

**Comment by tomasbrod** [comment]
Keep this open. The error message must be made more clean.
or create new issue and close this one?

**Comment by moisespr123** [comment]
Thinking about this, I think it's better to keep it open until solved just in case other members are having this issue as well.

**Comment by necrose99** [comment]
13:23:23
￼
execute advertisebeacon force


13:23:23
￼
[
{
"Command" : "advertisebeacon"
},
{
"Result" : "FAIL",
"CPID" : "",
"Message" : "",
"Errors" : "INVESTORS_CANNOT_SEND_BEACONS",
"FAILURE" : "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}
]
have patience ..... since jan 2018 its brooke on windows

**Comment by iFoggz** [comment]
check ur debug.log and see if the wallet detects your client state xml for boinc.

**Comment by necrose99** [comment]
netsh advfirewall firewall add rule name="GridcoinResearch" protocol=TCP dir=in localport=1433 action=allow try for upgraade no go... 

giving the port fix a go...

**Comment by iFoggz** [comment]
in client upgrade has been disabled for awhile.

**Comment by necrose99** [comment]
CPID=5aeeb0ab5bc858c726b5664e9e04d3ee
PrimaryCPID=5aeeb0ab5bc858c726b5664e9e04d3ee

![capture](https://user-images.githubusercontent.com/2396239/39720873-431cb1be-5203-11e8-8126-9b2a88723280.PNG)


[https://boincstats.com/en/stats/-1/user/detail/2244568/charts](https://boincstats.com/en/stats/-1/user/detail/2244568/charts)


#datadir=
boincappdir=C:\Program Files\BOINC 
#boincdatadir=/var/lib/boinc-client/
boincdatadir=C:\ProgramData\BOINC
#boincdatadir=/Library/Application Support/BOINC Data
CPID=5aeeb0ab5bc858c726b5664e9e04d3ee
email=my user @ my host.no spamz plz......
#PrimaryCPID=5aeeb0ab5bc858c726b5664e9e04d3ee
## Use as many addnode= settings as you like to connect to specific peers
addnode=grcnode.tahvok.com
addnode=grcexplorer.neuralminer.io
addnode=grcnode01.neuralminer.io
addnode=grcnode02.neuralminer.io
addnode=grcnode03.neuralminer.io
addnode=grcnode04.neuralminer.io
addnode=grcnode05.neuralminer.io
addnode=gridcoin.bunnyfeet.fi
addnode=gridcoin.certic.info
addnode=gridcoin.crypto.fans
addnode=gridcoin.hopto.org
addnode=ils.gridcoin.co.il
addnode=la.grcnode.co.uk
addnode=london.grcnode.co.uk
addnode=miami.grcnode.co.uk
addnode=node.gridcoin.network
addnode=node.gridcoin.us
addnode=node.gridcoinapp.xyz
addnode=node1.chick3nman.com
addnode=nuad.de
addnode=quebec.gridcoin.co.il
addnode=seeds.gridcoin.ifoggz-network.xyz
addnode=singapore.grcnode.co.uk
addnode=toronto01.gridcoin.ifoggz-network.xyz
addnode=vancouver01.gridcoin.ifoggz-network.xyz
addnode=node.gridcoin.us 
addnode=www.grcpool.com 
addnode=seeds.gridcoin.ifoggz-network.xyz 
## Alternatively use as many connect= settings as you like to connect ONLY to specific peers
#connect=
#listen=1
#maxconnections=
#maxoutboundconnections=
NEURAL_07252017=CLEARING
UpdatingLeaderboard=false
enablespeech=true
suppressupgrade=false
#daemon=1
#rpcuser=<username>
#rpcpassword=<password>
#server=1

**Comment by iFoggz** [comment]
Ur wallet must be fully synced

**Comment by tomasbrod** [comment]
You do not _need_ port 1433, neither 32749. Port 32749 helps to speed up sync, but is not strictly required for normal operation and really has nothing to do with beacon advertise. Port triggering will probably not work for Gridcoin, however it is the same security level as straight opening the port. If your firewall software is blocking _outgoing_ ports (not incoming, blocking those is OK) from the ephemeral range by default, then please report a bug to it's maintainers.

Your problem @necrose99, is that the wallet is not detecting your CPID. Without CPID it is in investor mode, and thus the message INVESTORS_CANNOT_SEND_BEACONS. This is usually caused by improper configuration of `boincdatadir` options. Check that those point to your valid boinc directory, with `client_state.xml` file in it, and that there is a sash at the end of the path.
1) On windows, path separators MUST be `\\` (double back slashes)
2) There must be a separator at the end of path (`/` or `\\`)

The second reason being improper configuration of `email` option. Also if you specify `PrimaryCPID`, make sure it is matching cpids of your projects, otherwise do not specify it at all.

**Comment by jamescowens** [comment]
I am closing this issue, as it appears the root issue was addressed with no further feedback.
